openapi: 3.0.3
info:
  title: Banking API Specification for account operations
  description: |-
    A simple banking API that allows two operations:
    - get account balance given account number
    - deposit amount to a account
  version: 1.0-SNAPSHOT
servers:
  - url: https://testenvironment.org/api/v1
  - url: https://prodenvironment.org/api/v1
tags:
  - name: accounts
    description: Operations between bank accounts
paths:
  /raft:
    get:
      requestBody:
        $ref: '#/components/requestBodies/RaftPayloadBody'
      responses:
        200:
          description: 'Updated'

components:
  requestBodies: # https://swagger.io/docs/specification/describing-request-body/
    RaftPayloadBody:
      description: 'The Raft protocol body'
      required: true
      content:
        application/json:
          schema:
            anyOf:
              - $ref: '#/components/schemas/VoteRequestModel'
              - $ref: '#/components/schemas/VoteResponseModel'
  schemas:
    VoteRequestModel:
      allOf:
        - $ref: 'VoteRequest'
    VoteResponseModel:
      allOf:
        - $ref: 'VoteResponse'