services:
  # https://hub.docker.com/_/postgres
  # https://codepruner.com/how-to-run-postgresql-and-adminer-or-pgadmin-with-docker-compose/
  db:
    container_name: db
    image: postgres:latest
    restart: always
    networks:
      host: {}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5435
    volumes:
      - ./target/postgres_data:/var/lib/postgresql/data
      # https://stackoverflow.com/questions/26598738/how-to-create-user-database-in-script-for-docker-postgres
      - ./src/main/resources/dml/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    # https://www.postgresql.org/docs/current/runtime-config-wal.html
    command: [ "postgres", "-c", "wal_level=replica" ] # replica is default, wal_level=logical
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    networks:
      host: {}
    depends_on:
      - db
    ports:
      - 8080:8080

# docker networking!
# https://stackoverflow.com/questions/56582446/how-to-use-host-network-for-docker-compose
# https://stackoverflow.com/questions/70725881/what-is-the-equivalent-of-add-host-host-docker-internalhost-gateway-in-a-comp
# networks:
#  mynetwork:
#    external: true
#    name: host
networks:
  host:
    name: host
    external: true